### ISSUE TITLE
ModuleNotFoundError: No module named 'pyidaungsu.model.lib.fasttext_pybind'

### ISSUE THREAD

**Issue by learnercat** [kaunghtetsan275/pyidaungsu#1]
Hi! Thank you very much for your great work. 
I have just installed and tested it in Python Version 3.6 in the Anaconda environment (Ubuntu 18.04.4 LTS). I got the ModuleNotFoundError. Please help.

Here's the error details:

`ModuleNotFoundError                       Traceback (most recent call last)`
`<ipython-input-2-04e0d58c0486> in <module>`
`----> 1 import pyidaungsu as pds`
`~/anaconda3/envs/py36/lib/python3.6/site-packages/pyidaungsu-0.0.9-py3.6.egg/pyidaungsu/__init__.py in <module>`
`1 from pyidaungsu.tokenize import Tokenize`
`2 import emoji`
`----> 3 import pyidaungsu.model.lib.fasttext_pybind as fasttext`
`4 import re, os`
`5 import numpy as np`
`ModuleNotFoundError: No module named 'pyidaungsu.model.lib.fasttext_pybind'`

**Comment by kaunghtetsan275** [comment]
I suspect it might be because of the conda environment. Try reinstalling it with virtualenv instead of anaconda

**Comment by learnercat** [comment]
Thanks @kaunghtetsan275 . Now it works on the pure Python 3.8 of Ubuntu.
