### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by Andro6** [kaunghtetsan275/pyidaungsu#2]
Unicode Error with character map.....

**Comment by kaunghtetsan275** [comment]
Could you provide stack trace including error message?

**Comment by Andro6** [comment]
![Untitled](https://user-images.githubusercontent.com/40929882/90337022-a8d1c700-e005-11ea-8dbb-5bdd036f3c0e.png)

**Comment by kaunghtetsan275** [comment]
sry for the late reply .. it was an issue in the setup file .. will fix in the next release ..

**Comment by Andro6** [comment]
okay bro....
I am waiting your update version.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
