### ISSUE TITLE
No module named 'pyidaungsu.model.lib.fasttext_pybind'

### ISSUE THREAD

**Issue by juartaurus98** [kaunghtetsan275/pyidaungsu#3]
I install pyidaungsu on gg.colab and ubuntu 18.04, and have this error. I checked in pyidaungsu.model.lib, and file "_fasttext_pybind.cpython-38-x86_64-linux-gnu.so_" is exist. Why cant i import it?

**Comment by dxcore35** [comment]
SAME HERE:

 from pyidaungsu.tokenize import Tokenize
      2 import emoji
----> 3 import pyidaungsu.model.lib.fasttext_pybind as fasttext
      4 import re, os
      5 import numpy as np

ModuleNotFoundError: No module named 'pyidaungsu.model.lib.fasttext_pybind'

**Comment by kaunghtetsan275** [comment]
There seems to be an error in importing the compiled fasttext_pybind library from C++. I lost the original data required to train the detection model. I will need to start over and look into this issue.

**Comment by DanielCollins** [comment]
I still see this issue in 0.0.9. 0.0.8 works.

**Comment by kaunghtetsan275** [comment]
@DanielCollins Thanks for trying it out. I've made a new release 0.1.0 which should work as expected. You can install it from source code or from pip as:

`pip install --no-cache-dir pyidaungsu`

**Comment by DanielCollins** [comment]
0.1.0 actually breaks the python interpreter. After importing pds, expressions no longer print any result.I've never seen that happen before.

    Python 3.9.5 (default, May 17 2021, 02:59:20) 
    [Clang 9.1.0 (clang-902.0.39.2)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> 4 + 6
    10
    >>> 4 > 5
    False
    >>> import pyidaungsu as pds
    >>> 4 > 5
    >>> 4 + 6
    >>>  pds.detect("ထမင်းစားပြီးပြီလား")
    >>> type(pds.detect("ထမင်းစားပြီးပြီလား"))
    
...  the repl is dead ...

**Comment by kaunghtetsan275** [comment]
The problem lies in __init__.py , line 7. I meant to suppress error warning from imports but it seemed to disable all console output unnecessarily. You can either remove the line or comment it out manually in the package directory or make a fresh install again with

`pip install -U pyidaungsu`

**Comment by kaunghtetsan275** [comment]
> After importing pds, expressions no longer print any result.

@DanielCollins  Let me know if it doesn't work out yet.

**Comment by DanielCollins** [comment]
pyidaungsu-0.1.2 seems to be good. thank you for your work!

**Comment by DanielCollins** [comment]
there's still an issue, normal expression results are printed, but all exceptions go into a black hole. e.g.:

    >>> import pyidaungsu as pds
    >>> 4  > 5
    False
    >>> raise ValueError
    >>>

**Comment by DanielCollins** [comment]
makes it difficult to debug scripts -- python just quits with no message

**Comment by kaunghtetsan275** [comment]
@DanielCollins Fixed it in 0,1.4 and there won't be similar error like this in the future. Upgrade to 0.1.4.
`pip install -U pyidaungsu`

**Comment by DanielCollins** [comment]
thanks, it looks great now
