### ISSUE TITLE
Cannot detect mixed languages, only shows the language of last part.

### ISSUE THREAD

**Issue by thawzi** [kaunghtetsan275/pyidaungsu#5]
import pyidaungsu as pds
language= pds.detect ("ထမင်းစားပြီးပြီလား၊ ထမင္းစားၿပီးၿပီလား၊ ၢ်သိၣ်လိတၢ်ဖးလံာ် ကွဲးလံာ်အိၣ်လၢ မ့ရ့ၣ်အစုပူၤလီၤ.")
print (language)
>>Shan

In this case, only Shan is shown. If MultiLang or MixedLang tag is shown, it will be better.

pds.detect ("Hi its me")
>>spanish
pds.detect ("Hi its me.")
>>eng

For the second part, only period determines if the lang is Spanish or English.

**Comment by kaunghtetsan275** [comment]
@thawzi the model is experimental. it needs some more work to be able to use this reliably. thanks for addressing the issue.
